# Consultas e Visualizações no Banco

Neste notebook são demonstrados os comandos SELECT para realizar consultas e visualizações no banco de dados que está em um contêiner do Docker.

#### Visualização da tabela pokemon

In [16]:
import pandas as pd
import psycopg2
import time

while True:
    try:
        conexao = psycopg2.connect(
            host="localhost",
            port=5432,
            database="silver_db",
            user="silver_user",
            password="silver_password"
        )
        break
    except psycopg2.OperationalError:
        print("O banco não está pronto, aguardando 3 segundos...")
        time.sleep(3)

# cria o cursor
cursor = conexao.cursor()

cursor.execute("""
    SELECT * FROM pokemon; 
""")

# visualizar os resultados
dados = cursor.fetchall() # Captura os resultados 
colunas = [desc[0] for desc in cursor.description] # Captura os nomes das colunas
df = pd.DataFrame(dados, columns=colunas) # Cria um DataFrame para exibir
display(df) # Exibe o DataFrame 


# Fechando conexão
cursor.close()
conexao.close()

,pokedex_number,pokemon_name,type_1,type_2,height,weight,hit_points,attack,defense,total_stats,...,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy
0,1,Bulbasaur,Grass,Poison,0.7,6.9,45,49,49,318,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
1,2,Ivysaur,Grass,Poison,1.0,13.0,60,62,63,405,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
2,3,Mega Venusaur,Grass,Poison,2.4,155.5,80,100,123,625,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
3,4,Charmander,Fire,Indefinido,0.6,8.5,39,52,43,309,...,2.0,1.0,1.0,0.5,2.0,1.0,1.0,1.0,0.5,0.5
4,5,Charmeleon,Fire,Indefinido,1.1,19.0,58,64,58,405,...,2.0,1.0,1.0,0.5,2.0,1.0,1.0,1.0,0.5,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
893,894,Regieleki,Electric,Indefinido,1.2,145.0,80,100,50,580,...,2.0,0.5,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0
894,895,Regidrago,Dragon,Indefinido,2.1,200.0,200,100,50,580,...,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0
895,896,Glastrier,Ice,Indefinido,2.2,800.0,100,145,130,580,...,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0
896,897,Spectrier,Ghost,Indefinido,2.0,44.5,100,65,60,580,...,1.0,1.0,1.0,0.5,1.0,2.0,1.0,2.0,1.0,1.0
897,898,Calyrex,Psychic,Grass,1.1,7.7,100,80,80,500,...,0.5,2.0,0.5,4.0,1.0,2.0,1.0,2.0,1.0,1.0

#### Consulta dos nomes dos pokémons presentes na tabela pokemon

In [17]:
import pandas as pd
import psycopg2
import time

while True:
    try:
        conexao = psycopg2.connect(
            host="localhost",
            port=5432,
            database="silver_db",
            user="silver_user",
            password="silver_password"
        )
        break
    except psycopg2.OperationalError:
        print("O banco não está pronto, aguardando 3 segundos...")
        time.sleep(3)

# cria o cursor
cursor = conexao.cursor()

cursor.execute("""
    SELECT pokemon_name FROM pokemon; 
""")
# visualizar os resultados
dados = cursor.fetchall() # Captura os resultados 
colunas = [desc[0] for desc in cursor.description] # Captura os nomes das colunas
df = pd.DataFrame(dados, columns=colunas) # Cria um DataFrame para exibir
display(df) # Exibe o DataFrame 

# Fechando conexão
cursor.close()
conexao.close()

      pokemon_name
0        Bulbasaur
1          Ivysaur
2    Mega Venusaur
3       Charmander
4       Charmeleon
..             ...
893      Regieleki
894      Regidrago
895      Glastrier
896      Spectrier
897        Calyrex

[898 rows x 1 columns]

#### Consulta dos Pokémon que são do tipo 'Fire' (Fogo)

In [ ]:
import pandas as pd
import psycopg2
import time

while True:
    try:
        conexao = psycopg2.connect(
            host="localhost",
            port=5432,
            database="silver_db",
            user="silver_user",
            password="silver_password"
        )
        break
    except psycopg2.OperationalError:
        print("O banco não está pronto, aguardando 3 segundos...")
        time.sleep(3)


cursor = conexao.cursor()


cursor.execute("""
    SELECT pokemon_name, type_1, type_2 FROM pokemon WHERE type_1 = 'Fire';
""")

print("Resultado da consulta:")
dados = cursor.fetchall()
colunas = [desc[0] for desc in cursor.description]
df = pd.DataFrame(dados, columns=colunas)
display(df)

cursor.close()
conexao.close()
print("Conexão com o banco de dados fechada.")

Resultado da consulta:

            pokemon_name type_1      type_2
0             Charmander   Fire  Indefinido
1             Charmeleon   Fire  Indefinido
2              Charizard   Fire      Flying
3              Growlithe   Fire  Indefinido
4               Arcanine   Fire  Indefinido
5         Alolan Marowak   Fire       Ghost
6                 Magmar   Fire  Indefinido
7                Flareon   Fire  Indefinido
8              Cyndaquil   Fire  Indefinido
9                Quilava   Fire  Indefinido
10            Typhlosion   Fire  Indefinido
11                Slugma   Fire  Indefinido
12              Magcargo   Fire        Rock
13                 Magby   Fire  Indefinido
14                 Entei   Fire  Indefinido
15                 Ho-Oh   Fire      Flying
16               Torchic   Fire  Indefinido
17             Combusken   Fire    Fighting
18              Blaziken   Fire    Fighting
19                 Numel   Fire      Ground
20              Camerupt   Fire      Ground
21               Torkoal   Fire  Indefinido
22              Chimchar   Fire  Indefinido
23              Monferno   Fire    Fighting
24             Infernape   Fire    Fighting
25             Magmortar   Fire  Indefinido
26               Heatran   Fire       Steel
27                 Tepig   Fire  Indefinido
28               Pignite   Fire    Fighting
29                Emboar   Fire    Fighting
30               Pansear   Fire  Indefinido
31              Simisear   Fire  Indefinido
32              Darumaka   Fire  Indefinido
33            Darmanitan   Fire  Indefinido
34               Heatmor   Fire  Indefinido
35              Fennekin   Fire  Indefinido
36               Braixen   Fire  Indefinido
37               Delphox   Fire     Psychic
38           Fletchinder   Fire      Flying
39            Talonflame   Fire      Flying
40                Litleo   Fire      Normal
41                Pyroar   Fire      Normal
42             Volcanion   Fire       Water
43                Litten   Fire  Indefinido
44              Torracat   Fire  Indefinido
45            Incineroar   Fire        Dark
46  Oricorio Baile Style   Fire      Flying
47            Turtonator   Fire      Dragon
48           Blacephalon   Fire       Ghost
49             Scorbunny   Fire  Indefinido
50                Raboot   Fire  Indefinido
51             Cinderace   Fire  Indefinido
52            Sizzlipede   Fire         Bug
53           Centiskorch   Fire         Bug

Conexão com o banco de dados fechada.

#### Top 10 Pokémon Mais Pesados

In [4]:
import pandas as pd
import psycopg2
import time

while True:
    try:
        conexao = psycopg2.connect(
            host="localhost", 
            port=5432, 
            database="silver_db", 
            user="silver_user", 
            password="silver_password"
        )
        break
    except psycopg2.OperationalError:
        print("O banco não está pronto, aguardando 3 segundos...")
        time.sleep(3)

cursor = conexao.cursor()

cursor.execute("""
    SELECT pokemon_name, weight, type_1
    FROM pokemon
    ORDER BY weight DESC
    LIMIT 10;
""")

print("Resultado da consulta:")
dados = cursor.fetchall()
colunas = [desc[0] for desc in cursor.description]
df = pd.DataFrame(dados, columns=colunas)
display(df)

cursor.close()
conexao.close()
print("Conexão fechada.")

Resultado da consulta:

     pokemon_name  weight   type_1
0         Cosmoem   999.9  Psychic
1      Celesteela   999.9    Steel
2         Groudon   950.0   Ground
3       Eternatus   950.0   Poison
4  Mega Metagross   942.9    Steel
5        Mudsdale   920.0   Ground
6        Guzzlord   888.0     Dark
7       Stakataka   820.0     Rock
8        Melmetal   800.0    Steel
9       Glastrier   800.0      Ice

Conexão fechada.

#### Pokémon Lendários e Míticos da Primeira Geração

In [5]:
import pandas as pd
import psycopg2
import time

while True:
    try:
        conexao = psycopg2.connect(
            host="localhost", 
            port=5432, 
            database="silver_db", 
            user="silver_user", 
            password="silver_password")
        break
    except psycopg2.OperationalError:
        print("O banco não está pronto, aguardando 3 segundos...")
        time.sleep(3)

cursor = conexao.cursor()

cursor.execute("""
    SELECT pokedex_number, pokemon_name, type_1, type_2, total_stats
    FROM pokemon
    WHERE generation = 1 AND (legendary = TRUE OR mythical = TRUE)
    ORDER BY pokedex_number;
""")

print("Resultado da consulta:")
dados = cursor.fetchall()
colunas = [desc[0] for desc in cursor.description]
df = pd.DataFrame(dados, columns=colunas)
display(df)

cursor.close()
conexao.close()
print("Conexão fechada.")

Resultado da consulta:

   pokedex_number pokemon_name   type_1      type_2  total_stats
0             144     Articuno      Ice      Flying          580
1             151          Mew  Psychic  Indefinido          600

Conexão fechada.

#### Pokémon com dois tipos e Total Stats acima de 600

In [6]:
import pandas as pd
import psycopg2
import time

while True:
    try:
        conexao = psycopg2.connect(
            host="localhost", 
            port=5432, 
            database="silver_db", 
            user="silver_user", 
            password="silver_password")
        break
    except psycopg2.OperationalError:
        print("O banco não está pronto, aguardando 3 segundos...")
        time.sleep(3)

cursor = conexao.cursor()

cursor.execute("""
    SELECT pokemon_name, type_1, type_2, total_stats
    FROM pokemon
    WHERE total_stats > 600 AND type_2 != 'Indefinido'
    ORDER BY total_stats DESC;
""")

print("Resultado da consulta:")
dados = cursor.fetchall()
colunas = [desc[0] for desc in cursor.description]
df = pd.DataFrame(dados, columns=colunas)
display(df)

cursor.close()
conexao.close()
print("Conexão fechada.")

Resultado da consulta:

                pokemon_name    type_1    type_2  total_stats
0              Mega Mewtwo X   Psychic  Fighting          780
1              Mega Rayquaza    Dragon    Flying          780
2       Zacian Crowned Sword     Fairy     Steel          720
3   Zamazenta Crowned Shield  Fighting     Steel          720
4             Mega Salamence    Dragon    Flying          700
5               Black Kyurem    Dragon       Ice          700
6             Mega Tyranitar      Rock      Dark          700
7             Mega Metagross     Steel   Psychic          700
8                  Eternatus    Poison    Dragon          690
9                     Dialga     Steel    Dragon          680
10                     Lugia   Psychic    Flying          680
11                     Ho-Oh      Fire    Flying          680
12                    Palkia     Water    Dragon          680
13          Giratina Altered     Ghost    Dragon          680
14                  Reshiram    Dragon      Fire          680
15                    Zekrom    Dragon  Electric          680
16                   Yveltal      Dark    Flying          680
17                  Solgaleo   Psychic     Steel          680
18                    Lunala   Psychic     Ghost          680
19             Mega Swampert     Water    Ground          635
20             Mega Sceptile     Grass    Dragon          630
21             Mega Venusaur     Grass    Poison          625
22              Mega Steelix     Steel    Ground          610

Conexão fechada.

#### Contagem de Pokémon por Tipo Primário

In [7]:
import pandas as pd
import psycopg2
import time

while True:
    try:
        conexao = psycopg2.connect(
            host="localhost", 
            port=5432, 
            database="silver_db", 
            user="silver_user", 
            password="silver_password")
        break
    except psycopg2.OperationalError:
        print("O banco não está pronto, aguardando 3 segundos...")
        time.sleep(3)

cursor = conexao.cursor()

cursor.execute("""
    SELECT type_1, COUNT(pokedex_number) AS quantidade
    FROM pokemon
    GROUP BY type_1
    ORDER BY quantidade DESC;
""")

print("Resultado da consulta:")
dados = cursor.fetchall()
colunas = [desc[0] for desc in cursor.description]
df = pd.DataFrame(dados, columns=colunas)
display(df)

cursor.close()
conexao.close()
print("Conexão fechada.")

Resultado da consulta:

      type_1  quantidade
0      Water         120
1     Normal         103
2      Grass          86
3        Bug          75
4    Psychic          60
5       Fire          54
6       Rock          50
7   Electric          48
8       Dark          43
9   Fighting          37
10    Poison          37
11       Ice          33
12    Ground          33
13    Dragon          31
14     Ghost          30
15     Steel          30
16     Fairy          21
17    Flying           7

Conexão fechada.

#### Consulta: Super Fracos contra Fogo (Dano 4x)

In [10]:
import pandas as pd
import psycopg2
import time

while True:
    try:
        conexao = psycopg2.connect(
            host="localhost", 
            port=5432, 
            database="silver_db", 
            user="silver_user", 
            password="silver_password")
        break
    except psycopg2.OperationalError:
        print("O banco não está pronto, aguardando 3 segundos...")
        time.sleep(3)

cursor = conexao.cursor()

cursor.execute("""
    SELECT pokemon_name, type_1, type_2, against_fire
    FROM pokemon
    WHERE against_fire = 4.0;
""")

print("Resultado da consulta:")
dados = cursor.fetchall()
colunas = [desc[0] for desc in cursor.description]
df = pd.DataFrame(dados, columns=colunas)
display(df)

cursor.close()
conexao.close()
print("Conexão fechada.")

Resultado da consulta:

            pokemon_name type_1 type_2  against_fire
0       Alolan Sandshrew    Ice  Steel           4.0
1       Alolan Sandslash    Ice  Steel           4.0
2                  Paras    Bug  Grass           4.0
3               Parasect    Bug  Grass           4.0
4             Forretress    Bug  Steel           4.0
5            Mega Scizor    Bug  Steel           4.0
6   Wormadam Plant Cloak    Bug  Grass           4.0
7                 Snover  Grass    Ice           4.0
8              Abomasnow  Grass    Ice           4.0
9               Sewaddle    Bug  Grass           4.0
10              Swadloon    Bug  Grass           4.0
11              Leavanny    Bug  Grass           4.0
12            Escavalier    Bug  Steel           4.0
13             Ferroseed  Grass  Steel           4.0
14            Ferrothorn  Grass  Steel           4.0
15                Durant    Bug  Steel           4.0
16              Genesect    Bug  Steel           4.0
17               Kartana  Grass  Steel           4.0
18                  Snom    Ice    Bug           4.0
19              Frosmoth    Ice    Bug           4.0

Conexão fechada.

#### Consulta: "Canhões de Vidro" (Ataque > 110 e Defesa < 70)

In [ ]:
import pandas as pd
import psycopg2
import time

while True:
    try:
        conexao = psycopg2.connect(
            host="localhost", 
            port=5432, 
            database="silver_db", 
            user="silver_user", 
            password="silver_password")
        break
    except psycopg2.OperationalError:
        print("O banco não está pronto, aguardando 3 segundos...")
        time.sleep(3)

cursor = conexao.cursor()

cursor.execute("""
    SELECT pokemon_name, attack, defense, total_stats
    FROM pokemon
    WHERE attack > 110 AND defense < 70
    ORDER BY attack DESC;
""")

print("Resultado da consulta:")
dados = cursor.fetchall()
colunas = [desc[0] for desc in cursor.description]
df = pd.DataFrame(dados, columns=colunas)
display(df)

cursor.close()
conexao.close()
print("Conexão fechada.")

Conexão estabelecida!
Resultado da consulta:

          pokemon_name  attack  defense  total_stats
0   Deoxys Attack Form     180       20          600
1            Rampardos     165       60          495
2           Darmanitan     140       55          480
3             Archeops     140       65          567
4            Pheromosa     137       37          570
5            Excadrill     135       60          508
6              Flareon     130       60          525
7           Copperajah     130       69          500
8                Absol     130       60          465
9          Blacephalon     127       53          570
10           Honchkrow     125       52          505
11             Gallade     125       65          518
12            Mienshao     125       60          510
13            Cranidos     125       40          350
14              Emboar     123       65          528
15          Electivire     123       67          540
16         Barraskewda     123       60          490
17           Hitmonlee     120       53          455
18            Hariyama     120       60          474
19             Weavile     120       65          510
20          Grimmsnarl     120       65          510
21       Lycanroc Dusk     117       65          487
22            Zangoose     115       60          458
23             Banette     115       65          455
24              Komala     115       65          480
25            Cacturne     115       60          475
26         Centiskorch     115       65          525
27              Archen     112       45          401

Conexão fechada.